name: Release

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write


jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        pre_command: |
          echo "machine github.com login ${{ github.actor }} password ${{ secrets.MICK_GITHUB_TOKEN  }}" > ~/.netrc
          chmod 600 ~/.netrc
          git config --global --add url."https://github.com/".insteadOf "ssh://git@github.com/"
          git config --global --add url."https://github.com/".insteadOf "git@github.com"   
          go env -w GOPRIVATE=github.com/upsun/*
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: "./cmd/"
        build_flags: -v
        ldflags:  -X "version.VERSION=${{ github.ref_name }}"
        # -X "main.buildTime=${{ env.BUILD_TIME }}" -X main.gitCommit=${{ github.sha }} -X main.gitRef=${{ github.ref }}
        extra_files: LICENSE README.md